#!/bin/bash

SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $SCRIPTDIR/chip_nand_scripts_common

require ubinize "Please install mtd-utils"
require img2simg "Please install fastboot-utils"

# build the UBI image
prepare_ubi() {
  local ubi="$1"
  local ubifs="$2"
  local ubicfg="$3"
  local nandtype="$4"
  local maxlebcount="$5"
  local eraseblocksize="$6"
  local pagesize="$7"
  local subpagesize="$8"

  local sparseubi="${ubi}.sparse"
  local mlcopts=""

  if [ -z $subpagesize ]; then
    subpagesize=$pagesize
  fi

  if [ "$nandtype" = "mlc" ]; then
    lebsize=$((eraseblocksize/2-$pagesize*2))
    mlcopts="-M dist3"
  elif [ $subpagesize -lt $pagesize ]; then
    lebsize=$((eraseblocksize-pagesize))
  else
    lebsize=$((eraseblocksize-pagesize*2))
  fi

  echo "WARNING: not applying MLC fixed nand size work around..."

  echo ubinize -o $ubi -p $eraseblocksize -m $pagesize -s $subpagesize $mlcopts $ubicfg
  ubinize -o $ubi -p $eraseblocksize -m $pagesize -s $subpagesize $mlcopts $ubicfg
  img2simg $ubi $sparseubi $eraseblocksize
}

usage() {
  echo -e "\n\
  usage: $(basename $0) [options] INPUTFILE\n\
\n
  options:\n\
    -N FILENAME         - read nand configuration from FILENAME\n\
    -c FILENAME         - read ubinize configuration from FILENAME\n\
    -d OUTPUTDIR        - write file to OUTPUTDIR (default: .)\n\
    -o OUTPUTFILE       - write to OUTPUTFILE (default: $outputdir/chip-$NAND_EBSIZE-$NAND_PSIZE.ubi)n\
    -h, --help          - show this help\n\
\n"
  exit 1
}


while getopts ":N:d:o:c:" o; do
    case "${o}" in
        N)
            read_nand_config "${OPTARG}"
            ;;
        o)
            outputfile=${OPTARG}
            ;;
        d)
            outputdir=${OPTARG}
            ;;
        c)
            ubinize_cfg=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

ubinize_cfg="${ubinize_cfg:?ERROR: no ubinize configuration specified}"
outputdir="${outputdir:-.}"
outputfile="${outputfile:-$outputdir/chip-$NAND_EBSIZE-$NAND_PSIZE.ubi}"
inputfile="$1"

prepare_ubi "${outputfile}" "${inputfile}" "${ubinize_cfg}" $NAND_TYPE $NAND_MAXLEB_COUNT $NAND_ERASE_BLOCK_SIZE $NAND_PAGE_SIZE $NAND_SUBPAGE_SIZE
